export const ADHERENDS_KN = [
    { code: 'A', name: ' #ＳＵＳ３６０' },
    { code: 'B', name: ' #ＳＵＳ１２００' },
    { code: 'C', name: ' #ＨＡ５' },
    { code: 'D', name: ' #ＨＡ９' },
    { code: 'E', name: ' #フロート硝子３ｍｍ' },
    { code: 'F', name: ' #ポリイミド' },
    { code: 'G', name: ' #ソーダ硝子' },
    { code: 'H', name: ' #ＰＰ' },
    { code: 'I', name: ' #ＰＥ' },
    { code: 'J', name: ' #ＰＳ' },
    { code: 'K', name: ' #Ｓｉ' },
    { code: 'L', name: ' #ＡＢＳ' },
    { code: 'M', name: ' #アクリルオパール４３２' },
    { code: 'N', name: ' #メラミン塗装鉄板' },
    { code: 'O', name: ' #ボンデ鋼板' },
    { code: 'P', name: ' #ＳＵＳ１２００ＵＶ' },
    { code: 'Q', name: ' #ゴリラガラス２' },
    { code: 'R', name: ' #ポリイミド' },
    { code: 'S', name: ' #銅' },
];

export const ADHERENDS_HO = [
    { code: '01', name: ' #ＳＵＳ' },
    { code: '02', name: ' #ＰＥＮ' },
    { code: '03', name: ' #ＦＰ５０１１' },
    { code: '04', name: ' # ガラス板' },
    { code: '05', name: ' #ベーク' },
    { code: '06', name: ' #ＰＥ' },
    { code: '07', name: ' #鏡面ＳＵＳ' },
    { code: '08', name: ' #ＰＳ' },
    { code: '09', name: ' #＃６００研磨ＳＵＳ' },
    { code: '10', name: ' #メラミン塗装板' },
    { code: '11', name: ' #ＰＥＴ' },
    { code: '12', name: ' #鏡面　ＳＵＳ' },
    { code: '13', name: ' #ＰＩ' },
    { code: '14', name: ' #Ｃｕ' },
    { code: '15', name: ' #ＡＬ／ＰＥＴ間' },
    { code: '16', name: ' #ＥＶＡ／ＰＥＴ間' },
    { code: '17', name: ' #ＰＰ' },
    { code: '18', name: ' #ＰＶＣ' },
    { code: '19', name: ' #ＰＶＣ・タキロンプレート' },
    { code: '20', name: ' #アクリル板' },
    { code: '21', name: ' #ソーダガラス' },
    { code: '22', name: ' #ＮＦ　ＰＥＴトウメイ２５（Ｎ）' },
    { code: '23', name: ' #ガラス' },
    { code: '24', name: ' #アクリルオパール' },
    { code: '25', name: ' #ＰＥＴトウメイ５０（Ｎ）' },
    { code: '26', name: ' #ＰＣ' },
    { code: '27', name: ' #ＳＵＳ東洋指定' },
];